
services:
  web:
    image: arajetacrodsgroundsdev.azurecr.io/arajet-app-odsgrounds-dev:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEBSITE_USE_DIAGNOSTIC_SERVER=false
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITE_SITE_NAME=arajet-app-odsgrounds-dev
      - WEBSITE_AUTH_ENABLED=False
      - PORT=3000
    restart: always  
