services:
  app:
    image: node:18-alpine
    container_name: my-nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
