# docker-compose.yml
version: '3.8'

services:
  app:
    image: arajetacrodsgroundsdev.azurecr.io/ods_grounds_app:latest
    container_name: ods_grounds_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - NODE_ENV=production
