# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - arajet-app-odsgrounds-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://arajetacrodsgroundsdev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5a4cacb36cad40f69a5157a289a88821 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d232141a96864a98b7492ae57801df53 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: arajetacrodsgroundsdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a4cacb36cad40f69a5157a289a88821 }}/arajetacrodsgroundsdev/arajet-app-odsgrounds-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'arajet-app-odsgrounds-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3d5775550aba4bd39ce9f010967c38c5 }}
        images: 'arajetacrodsgroundsdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a4cacb36cad40f69a5157a289a88821 }}/arajetacrodsgroundsdev/arajet-app-odsgrounds-dev:${{ github.sha }}'