# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - arajet-app-odsgrounds-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: arajetacrodsgroundsdev.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_aff00bd45fdd44eabb8df28ee7f1c200 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_82535e4037214fe78eba9f1ff585a9fc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: arajetacrodsgroundsdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aff00bd45fdd44eabb8df28ee7f1c200 }}/arajet-app-odsgrounds-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'arajet-app-odsgrounds-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_12a10ab65d9c41059afa2247c088397e }}
        images: 'arajetacrodsgroundsdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aff00bd45fdd44eabb8df28ee7f1c200 }}/arajet-app-odsgrounds-dev:${{ github.sha }}'
